// Copyright © 2020 SpotHero, Inc. All rights reserved.

/// A quote for parking provided by SpotHero to a prospective renter.
/// This quote is generated by SpotHero, includes detailed pricing information,
/// and is guaranteed to be honored for the period of validity specified within
/// so long as no part of the originally issued quote has been modified.
public struct Quote: Codable {
    private enum CodingKeys: String, CodingKey {
        case order
        case items
        case totalPrice = "total_price"
        case advertisedPrice = "advertised_price"
    }
    
    /// Order line items, including reservation rate and applicable fees.
    public let order: QuoteOrder
    
    /// Bottom-line items, including order subtotal, discounts, and payments.
    public let items: [QuoteLineItem]
    
    /// Final price paid by the end-user.
    public let totalPrice: Currency
    
    /// The price SpotHero suggests displaying to users prior to them selecting a quote to purchase.
    ///
    /// `advertised_price` will not necessarily match `total_price`.
    /// `total_price` includes the base reservation rate in addition to any taxes and fees to be collected upon purchase.
    /// In contrast, the `advertised_price` is designed by SpotHero to maximize user conversion, and may omit some taxes and fees.
    /// SpotHero suggests using `advertised_price` when a user is comparison shopping among multiple rates.
    /// `advertised_price` should never be displayed to a user at checkout.
    /// Please use `total_price` and show all `items` in the `order` to your users.
    public let advertisedPrice: Currency
}
