// Copyright © 2020 SpotHero, Inc. All rights reserved.

/// A quote for parking provided by SpotHero to a prospective renter.
/// This quote is generated by SpotHero, includes detailed pricing information,
/// and is guaranteed to be honored for the period of validity specified within
/// so long as no part of the originally issued quote has been modified.
public struct Quote: Codable {
    private enum CodingKeys: String, CodingKey {
        case order
        case items
        case totalPrice = "total_price"
        case advertisedPrice = "advertised_price"
    }
    
    /// Order line items, including reservation rate and applicable fees.
    public let order: QuoteOrder
    
    /// Bottom-line items, including order subtotal, discounts, and payments.
    public let items: [QuoteLineItem]
    
    // WIP: Missing Docs
    public let totalPrice: Currency
    
    // WIP: Missing Docs
    public let advertisedPrice: Currency
}
